[project]
name = "cs336-basics"
version = "1.0.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch~=2.6.0",
    "numpy",
    "chz>=0.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
